### ISSUE TITLE
how do i set the imports url

### ISSUE THREAD

**Issue by snowlotus** [CanopyTax/single-spa-playground#3]
## Data dump

Applications:
```json
[
  {
    "framework": "vue",
    "name": "xubao",
    "pathPrefix": "/xubao"
  }
]
```

Import map:
```json
{
  "imports": {
    "xubao": "https://unpkg.com/xubao"
  }
}
```

**Comment by joeldenning** [comment]
Are you using vue-cli to serve your vue project? Or just a separate webpack config?

The import url should be something like `http://localhost:<PORT>/main.js`

**Comment by snowlotus** [comment]
yes,i am vue-cli to start a demo,and fill the import url `http://localhost:8084/#/app.js` and start the test,it blocked at the first step and show me the error `TypeError: Failed to fetch`

**Comment by joeldenning** [comment]
The `#` is probably wrong in the url. Try going directly to your URL in a browser tab and see if you can download the js file. Once the js file can be loaded in the browser tab, then you know you've found the right URL.

Also, in regards to Vue, I hope to create a vue-cli plugin for single-spa sometime this week that will make it easier to have vue-cli projects interop with single-spa.

**Comment by snowlotus** [comment]
ok,thank you . I am looking forward to it

**Comment by joeldenning** [comment]
Vue CLI plugin created. See https://github.com/CanopyTax/vue-cli-plugin-single-spa and https://single-spa.js.org/docs/ecosystem-vue.html
